name: build
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get install cmake clang-format clang-tidy
          sudo apt-get install libasound2-dev mesa-common-dev libx11-dev libxrandr-dev libxi-dev xorg-dev libgl1-mesa-dev libglu1-mesa-dev
      - name: Run clang-format
        run: clang-format --dry-run --Werror src/**/*.*pp
      - name: Run CMake
        run: cmake -S. -Bbuild
      - name: Run Make
        run: make -Cbuild
      - name: Run clang-tidy
        run: clang-tidy src/**/*.*pp -p build/

