name: build
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt install cmake
          sudo apt install clang-format
          sudo apt install clang-tidy
          sudo apt install xorg-dev libglu1-mesa-dev
      - name: Run clang-format
        run: clang-format --dry-run --Werror src/**/*.*pp
      - name: Run CMake
        run: cmake -S. -Bbuild
      - name: Run Make
        run: make -Cbuild
      - name: Run clang-tidy
        run: clang-tidy src/**/*.*pp -p build/

